[package]
name = "marginfi"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marginfi"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-bpf = ["test"]
test = []

[dependencies]
solana-program = "1.10"
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
static_assertions = "1.1.0"

[dev-dependencies]
solana-program-test = "1.10"
solana-logger = "1.10"
solana-sdk = "1.10"
assert_matches = "1.5.0"
pretty_assertions = "1.2.1"
bincode = "1.3.3"
bytemuck = "1.9.1"
